"""Add Review association table

Revision ID: 9680063f7f6b
Revises: e4fa742d0207
Create Date: 2023-11-13 09:32:45.117779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9680063f7f6b'
down_revision = 'e4fa742d0207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('beer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], name=op.f('fk_reviews_beer_id_beers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
