"""Add beer table

Revision ID: e2a09fd841ad
Revises: 268b48b68528
Create Date: 2023-11-06 11:18:57.386680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a09fd841ad'
down_revision = '268b48b68528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('beer_type', sa.String(), nullable=True),
    sa.Column('brewery', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beers')
    # ### end Alembic commands ###
